### ISSUE TITLE
Modifying ResponseData / Response

### ISSUE THREAD

**Issue by duesee** [djc/tokio-imap#26]
How would you go about changing the data in the Response? As far as I understand, `ResponseData` owns the parsed `Response` -- this is why e.g. the `data` field in the `BodySection` is `&[u8]` and not `Vec<u8>` -- am I right? So... for my use case I need to change the body freely (also resize it). How could I proceed? Do you have a suggestion?

**Comment by djc** [comment]
Can you tell me more about your use case? Why do you need to mutate the `ResponseData`?

**Comment by duesee** [comment]
I'm writing an IMAP Proxy and need to transform email bodies, i.e. the fetch response.

**Comment by djc** [comment]
In general it won't be feasible to modify the `Response` type itself, since it is constructed from slices. I could provide `ResponseData` with an API to get at the raw response bytes, which you could then clone and modify in whatever way is necessary... but it's not clear that you can reuse the imap-proto parser for it. Would that help (enough)?

**Comment by duesee** [comment]
I _think_ that an "owning" variant of the `Response` (and maybe some other types) would be useful. But let me first take a closer look. If I come up with a solution which works for me, I will come back here and comment.

**Comment by djc** [comment]
I suppose that would mostly be useful if there is also a serializer that turns a `Response` back into a byte stream. But I'm happy to discuss potential avenues for this stuff if you get something working!
