### ISSUE TITLE
atom_char and text_char accept too much

### ISSUE THREAD

**Issue by duesee** [djc/tokio-imap#77]
I interprete the prose value in https://github.com/djc/tokio-imap/blob/master/imap-proto/src/core.rs#L32 to reference CHAR, as in

```
CHAR = %x01-7F ; any 7-bit US-ASCII character excluding NUL
```
In this case, e.g. 0xff should not be accepted. But it is.

Same for https://github.com/djc/tokio-imap/blob/master/imap-proto/src/core.rs#L131

Should we follow Postel's law or should I fix it? I prefer not to postel :-)

**Comment by djc** [comment]
My position on Postel has so far been that I am unPostellian strict until the need to do otherwise has been proven. If there is a need otherwise, it should be documented in comments. So I'm fine with making this stricter. That said, I do see a bit of a trade-off: if the strict version introduces a lot of complexity, let's discuss if it's worth it. That's probably not the case here, though. 👍

**Comment by duesee** [comment]
`literal` parser also accepts 0x00.

**Comment by duesee** [comment]
Oh god, that was challenging. Learned a lot about git though :+1: Can this be closed?

**Comment by djc** [comment]
Yup! Hope the next thing will be easier.

The basic git rule is that squashing is much easier than splitting, so make your commits as small as possible. You can also look into a tool called git-absorb.
